package com.github.tanhao1410.thesis.management.mapper;

import com.github.tanhao1410.thesis.management.domain.AlarmDO;
import com.github.tanhao1410.thesis.management.domain.AlarmDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AlarmDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    long countByExample(AlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByExample(AlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insert(AlarmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insertSelective(AlarmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<AlarmDO> selectByExampleWithRowbounds(AlarmDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<AlarmDO> selectByExample(AlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    AlarmDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") AlarmDO record, @Param("example") AlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExample(@Param("record") AlarmDO record, @Param("example") AlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKeySelective(AlarmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKey(AlarmDO record);
}