package com.github.tanhao1410.thesis.management.mapper;

import com.github.tanhao1410.thesis.management.domain.HistoryAlarmDO;
import com.github.tanhao1410.thesis.management.domain.HistoryAlarmDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HistoryAlarmDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    long countByExample(HistoryAlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByExample(HistoryAlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insert(HistoryAlarmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insertSelective(HistoryAlarmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<HistoryAlarmDO> selectByExampleWithRowbounds(HistoryAlarmDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<HistoryAlarmDO> selectByExample(HistoryAlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    HistoryAlarmDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") HistoryAlarmDO record, @Param("example") HistoryAlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExample(@Param("record") HistoryAlarmDO record, @Param("example") HistoryAlarmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKeySelective(HistoryAlarmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history_alarm
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKey(HistoryAlarmDO record);
}