package com.github.tanhao1410.thesis.management.mapper;

import com.github.tanhao1410.thesis.management.domain.MonitoringItemDO;
import com.github.tanhao1410.thesis.management.domain.MonitoringItemDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitoringItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    long countByExample(MonitoringItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByExample(MonitoringItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insert(MonitoringItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insertSelective(MonitoringItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<MonitoringItemDO> selectByExampleWithRowbounds(MonitoringItemDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<MonitoringItemDO> selectByExample(MonitoringItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    MonitoringItemDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") MonitoringItemDO record, @Param("example") MonitoringItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExample(@Param("record") MonitoringItemDO record, @Param("example") MonitoringItemDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKeySelective(MonitoringItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKey(MonitoringItemDO record);
}