package com.github.tanhao1410.thesis.management.mapper;

import com.github.tanhao1410.thesis.management.domain.MonitoringRuleDO;
import com.github.tanhao1410.thesis.management.domain.MonitoringRuleDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitoringRuleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    long countByExample(MonitoringRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByExample(MonitoringRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insert(MonitoringRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insertSelective(MonitoringRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<MonitoringRuleDO> selectByExampleWithRowbounds(MonitoringRuleDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<MonitoringRuleDO> selectByExample(MonitoringRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    MonitoringRuleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") MonitoringRuleDO record, @Param("example") MonitoringRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExample(@Param("record") MonitoringRuleDO record, @Param("example") MonitoringRuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKeySelective(MonitoringRuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_rule
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKey(MonitoringRuleDO record);
}