package com.github.tanhao1410.thesis.management.mapper;

import com.github.tanhao1410.thesis.management.domain.MonitoringDataDO;
import com.github.tanhao1410.thesis.management.domain.MonitoringDataDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MonitoringDataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    long countByExample(MonitoringDataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByExample(MonitoringDataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insert(MonitoringDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int insertSelective(MonitoringDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<MonitoringDataDO> selectByExampleWithRowbounds(MonitoringDataDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    List<MonitoringDataDO> selectByExample(MonitoringDataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    MonitoringDataDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExampleSelective(@Param("record") MonitoringDataDO record, @Param("example") MonitoringDataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByExample(@Param("record") MonitoringDataDO record, @Param("example") MonitoringDataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKeySelective(MonitoringDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_data
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    int updateByPrimaryKey(MonitoringDataDO record);
}