package com.github.tanhao1410.thesis.management.domain;

public class DeviceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.group_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.ip
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.x
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.y
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.id
     *
     * @return the value of device.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.id
     *
     * @param id the value for device.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.name
     *
     * @return the value of device.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.name
     *
     * @param name the value for device.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.group_id
     *
     * @return the value of device.group_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.group_id
     *
     * @param groupId the value for device.group_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.ip
     *
     * @return the value of device.ip
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.ip
     *
     * @param ip the value for device.ip
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.x
     *
     * @return the value of device.x
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.x
     *
     * @param x the value for device.x
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.y
     *
     * @return the value of device.y
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.y
     *
     * @param y the value for device.y
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device.department
     *
     * @return the value of device.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device.department
     *
     * @param department the value for device.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}