package com.github.tanhao1410.thesis.management.domain;

public class GroupDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.description
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.x
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.y
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.id
     *
     * @return the value of group.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.id
     *
     * @param id the value for group.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.description
     *
     * @return the value of group.description
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.description
     *
     * @param description the value for group.description
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDescription(Long description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.x
     *
     * @return the value of group.x
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.x
     *
     * @param x the value for group.x
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.y
     *
     * @return the value of group.y
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.y
     *
     * @param y the value for group.y
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.department
     *
     * @return the value of group.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.department
     *
     * @param department the value for group.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}