package com.github.tanhao1410.thesis.management.domain;

import java.util.Date;

public class HistoryAlarmDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.rule_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.value
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.start_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history_alarm.end_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.id
     *
     * @return the value of history_alarm.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.id
     *
     * @param id the value for history_alarm.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.name
     *
     * @return the value of history_alarm.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.name
     *
     * @param name the value for history_alarm.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.device_id
     *
     * @return the value of history_alarm.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.device_id
     *
     * @param deviceId the value for history_alarm.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.rule_id
     *
     * @return the value of history_alarm.rule_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.rule_id
     *
     * @param ruleId the value for history_alarm.rule_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.value
     *
     * @return the value of history_alarm.value
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.value
     *
     * @param value the value for history_alarm.value
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.start_time
     *
     * @return the value of history_alarm.start_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.start_time
     *
     * @param startTime the value for history_alarm.start_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history_alarm.end_time
     *
     * @return the value of history_alarm.end_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history_alarm.end_time
     *
     * @param endTime the value for history_alarm.end_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}