package com.github.tanhao1410.thesis.management.domain;

import java.util.ArrayList;
import java.util.List;

public class MonitoringItemDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public MonitoringItemDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNull() {
            addCriterion("device_id is null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIsNotNull() {
            addCriterion("device_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceIdEqualTo(Long value) {
            addCriterion("device_id =", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotEqualTo(Long value) {
            addCriterion("device_id <>", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThan(Long value) {
            addCriterion("device_id >", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("device_id >=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThan(Long value) {
            addCriterion("device_id <", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdLessThanOrEqualTo(Long value) {
            addCriterion("device_id <=", value, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdIn(List<Long> values) {
            addCriterion("device_id in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotIn(List<Long> values) {
            addCriterion("device_id not in", values, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdBetween(Long value1, Long value2) {
            addCriterion("device_id between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andDeviceIdNotBetween(Long value1, Long value2) {
            addCriterion("device_id not between", value1, value2, "deviceId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdIsNull() {
            addCriterion("monitoring_id is null");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdIsNotNull() {
            addCriterion("monitoring_id is not null");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdEqualTo(Long value) {
            addCriterion("monitoring_id =", value, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdNotEqualTo(Long value) {
            addCriterion("monitoring_id <>", value, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdGreaterThan(Long value) {
            addCriterion("monitoring_id >", value, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdGreaterThanOrEqualTo(Long value) {
            addCriterion("monitoring_id >=", value, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdLessThan(Long value) {
            addCriterion("monitoring_id <", value, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdLessThanOrEqualTo(Long value) {
            addCriterion("monitoring_id <=", value, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdIn(List<Long> values) {
            addCriterion("monitoring_id in", values, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdNotIn(List<Long> values) {
            addCriterion("monitoring_id not in", values, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdBetween(Long value1, Long value2) {
            addCriterion("monitoring_id between", value1, value2, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andMonitoringIdNotBetween(Long value1, Long value2) {
            addCriterion("monitoring_id not between", value1, value2, "monitoringId");
            return (Criteria) this;
        }

        public Criteria andThresholdIsNull() {
            addCriterion("threshold is null");
            return (Criteria) this;
        }

        public Criteria andThresholdIsNotNull() {
            addCriterion("threshold is not null");
            return (Criteria) this;
        }

        public Criteria andThresholdEqualTo(String value) {
            addCriterion("threshold =", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdNotEqualTo(String value) {
            addCriterion("threshold <>", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdGreaterThan(String value) {
            addCriterion("threshold >", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdGreaterThanOrEqualTo(String value) {
            addCriterion("threshold >=", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdLessThan(String value) {
            addCriterion("threshold <", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdLessThanOrEqualTo(String value) {
            addCriterion("threshold <=", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdLike(String value) {
            addCriterion("threshold like", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdNotLike(String value) {
            addCriterion("threshold not like", value, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdIn(List<String> values) {
            addCriterion("threshold in", values, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdNotIn(List<String> values) {
            addCriterion("threshold not in", values, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdBetween(String value1, String value2) {
            addCriterion("threshold between", value1, value2, "threshold");
            return (Criteria) this;
        }

        public Criteria andThresholdNotBetween(String value1, String value2) {
            addCriterion("threshold not between", value1, value2, "threshold");
            return (Criteria) this;
        }

        public Criteria andParamIsNull() {
            addCriterion("param is null");
            return (Criteria) this;
        }

        public Criteria andParamIsNotNull() {
            addCriterion("param is not null");
            return (Criteria) this;
        }

        public Criteria andParamEqualTo(String value) {
            addCriterion("param =", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotEqualTo(String value) {
            addCriterion("param <>", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamGreaterThan(String value) {
            addCriterion("param >", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamGreaterThanOrEqualTo(String value) {
            addCriterion("param >=", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamLessThan(String value) {
            addCriterion("param <", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamLessThanOrEqualTo(String value) {
            addCriterion("param <=", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamLike(String value) {
            addCriterion("param like", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotLike(String value) {
            addCriterion("param not like", value, "param");
            return (Criteria) this;
        }

        public Criteria andParamIn(List<String> values) {
            addCriterion("param in", values, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotIn(List<String> values) {
            addCriterion("param not in", values, "param");
            return (Criteria) this;
        }

        public Criteria andParamBetween(String value1, String value2) {
            addCriterion("param between", value1, value2, "param");
            return (Criteria) this;
        }

        public Criteria andParamNotBetween(String value1, String value2) {
            addCriterion("param not between", value1, value2, "param");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionIsNull() {
            addCriterion("alarm_condition is null");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionIsNotNull() {
            addCriterion("alarm_condition is not null");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionEqualTo(String value) {
            addCriterion("alarm_condition =", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionNotEqualTo(String value) {
            addCriterion("alarm_condition <>", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionGreaterThan(String value) {
            addCriterion("alarm_condition >", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionGreaterThanOrEqualTo(String value) {
            addCriterion("alarm_condition >=", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionLessThan(String value) {
            addCriterion("alarm_condition <", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionLessThanOrEqualTo(String value) {
            addCriterion("alarm_condition <=", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionLike(String value) {
            addCriterion("alarm_condition like", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionNotLike(String value) {
            addCriterion("alarm_condition not like", value, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionIn(List<String> values) {
            addCriterion("alarm_condition in", values, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionNotIn(List<String> values) {
            addCriterion("alarm_condition not in", values, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionBetween(String value1, String value2) {
            addCriterion("alarm_condition between", value1, value2, "alarmCondition");
            return (Criteria) this;
        }

        public Criteria andAlarmConditionNotBetween(String value1, String value2) {
            addCriterion("alarm_condition not between", value1, value2, "alarmCondition");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monitoring_item
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 20 15:15:50 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table monitoring_item
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}