package com.github.tanhao1410.thesis.management.domain;

import java.util.Date;

public class MonitoringDataDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_data.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_data.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_data.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_data.rule_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_data.value
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_data.start_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Date startTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_data.id
     *
     * @return the value of monitoring_data.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_data.id
     *
     * @param id the value for monitoring_data.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_data.name
     *
     * @return the value of monitoring_data.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_data.name
     *
     * @param name the value for monitoring_data.name
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_data.device_id
     *
     * @return the value of monitoring_data.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_data.device_id
     *
     * @param deviceId the value for monitoring_data.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_data.rule_id
     *
     * @return the value of monitoring_data.rule_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_data.rule_id
     *
     * @param ruleId the value for monitoring_data.rule_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_data.value
     *
     * @return the value of monitoring_data.value
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_data.value
     *
     * @param value the value for monitoring_data.value
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_data.start_time
     *
     * @return the value of monitoring_data.start_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_data.start_time
     *
     * @param startTime the value for monitoring_data.start_time
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
}