package com.github.tanhao1410.thesis.management.domain;

public class MonitoringItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_item.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_item.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_item.monitoring_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long monitoringId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_item.threshold
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String threshold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_item.param
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monitoring_item.alarm_condition
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String alarmCondition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_item.id
     *
     * @return the value of monitoring_item.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_item.id
     *
     * @param id the value for monitoring_item.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_item.device_id
     *
     * @return the value of monitoring_item.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_item.device_id
     *
     * @param deviceId the value for monitoring_item.device_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_item.monitoring_id
     *
     * @return the value of monitoring_item.monitoring_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getMonitoringId() {
        return monitoringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_item.monitoring_id
     *
     * @param monitoringId the value for monitoring_item.monitoring_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setMonitoringId(Long monitoringId) {
        this.monitoringId = monitoringId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_item.threshold
     *
     * @return the value of monitoring_item.threshold
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getThreshold() {
        return threshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_item.threshold
     *
     * @param threshold the value for monitoring_item.threshold
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setThreshold(String threshold) {
        this.threshold = threshold == null ? null : threshold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_item.param
     *
     * @return the value of monitoring_item.param
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_item.param
     *
     * @param param the value for monitoring_item.param
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monitoring_item.alarm_condition
     *
     * @return the value of monitoring_item.alarm_condition
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getAlarmCondition() {
        return alarmCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monitoring_item.alarm_condition
     *
     * @param alarmCondition the value for monitoring_item.alarm_condition
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setAlarmCondition(String alarmCondition) {
        this.alarmCondition = alarmCondition == null ? null : alarmCondition.trim();
    }
}