package com.github.tanhao1410.thesis.management.domain;

public class UserGroupDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.group_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.user_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    private String department;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.id
     *
     * @return the value of user_group.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.id
     *
     * @param id the value for user_group.id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.group_id
     *
     * @return the value of user_group.group_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.group_id
     *
     * @param groupId the value for user_group.group_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.user_id
     *
     * @return the value of user_group.user_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.user_id
     *
     * @param userId the value for user_group.user_id
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.department
     *
     * @return the value of user_group.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.department
     *
     * @param department the value for user_group.department
     *
     * @mbg.generated Sat Feb 20 15:15:50 CST 2021
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }
}